### ISSUE TITLE
Unable to build typescript example

### ISSUE THREAD

**Issue by ZebraFlesh** [optimizely/fullstack-labs#30]
Attempted to follow the readme. Not sure if related to #27.
```
> cd packages/example-react-typescript
> npx lerna run build
npx: installed 669 in 31.302s
info cli using local version of lerna
lerna notice cli v3.4.3
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@optimizely/react-sdk'
lerna ERR! yarn run build stdout:
yarn run v1.16.0
$ rm -rf dist/ && node ./scripts/build.js

Building ES modules...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
/bin/sh: ./node_modules/.bin/rollup: No such file or directory
child_process.js:656
    throw err;
    ^

Error: Command failed: ./node_modules/.bin/rollup -c scripts/config.js -f es -o dist/react-sdk.mjs
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at exec (/Users/nope/git/fullstack-labs/packages/react-sdk/scripts/build.js:8:10)
    at Object.<anonymous> (/Users/nope/git/fullstack-labs/packages/react-sdk/scripts/build.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@optimizely/react-sdk'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

**Comment by mjc1283** [comment]
Hi ZebraFlesh,

Thanks for pointing out this issue. The README instructions are incorrect. We will correct the README. In the meantime, please run `yarn start` from the example-react-typescript directory to run this example.
